name: panara_dialogs
description: PanaraDialogs is a Dialog UI Kit. A minimal but beautiful design for Flutter Dialogs.
version: 0.1.5
homepage: https://github.com/PanaraStudios/panaradialogs

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/info.png
    - assets/confirm.png
